import type { DeveloperPlatformOptions, CLICommandDescriptor, ScaffoldResult, ProjectScaffoldOptions, PluginScaffoldOptions, AgentScaffoldOptions, EngineScaffoldOptions, WorkflowScaffoldOptions, DocumentationScaffoldOptions } from './types';
import { TemplateRegistry } from './TemplateRegistry';
import { PackageRegistry } from './PackageRegistry';
import { DeveloperDiagnostics } from './DeveloperDiagnostics';
import { LocalEmulator } from './LocalEmulator';

export interface DeveloperPlatformService {
  registerCLICommand(command: CLICommandDescriptor): void;
  listCommands(): CLICommandDescriptor[];
  executeCommand(name: string, args: string[]): Promise<ScaffoldResult | void>;
}

export class DeveloperPlatform implements DeveloperPlatformService {
  readonly templateRegistry = new TemplateRegistry();
  readonly packageRegistry = new PackageRegistry();
  readonly diagnostics = new DeveloperDiagnostics();
  readonly emulator: LocalEmulator;
  readonly commands = new Map<string, CLICommandDescriptor>();

  constructor(private readonly options?: DeveloperPlatformOptions) {
    this.emulator = new LocalEmulator(options?.orchestrator, options?.evaluationEngine);
    // register a few helpful default CLI commands that call scaffolding helpers
    try {
      this.registerCLICommand({
        name: 'create:project',
        description: 'Scaffold a new project',
        usage: 'create:project <name> <description>',
        handler: async (args: string[]) => {
          const [name, ...rest] = args;
          const desc = rest.join(' ') || 'Generated by 9JA Developer Platform';
          return this.scaffoldProject({ projectName: name ?? 'new-project', description: desc, language: 'typescript' as any });
        },
      });

      this.registerCLICommand({
        name: 'create:plugin',
        description: 'Scaffold a new plugin',
        usage: 'create:plugin <id> <name>',
        handler: async (args: string[]) => {
          const [id, name] = args;
          return this.scaffoldPlugin({ pluginId: id ?? 'plugin-unknown', name: name ?? 'Unnamed Plugin', description: 'Created via CLI', capabilities: [] as any });
        },
      });

      this.registerCLICommand({
        name: 'create:engine',
        description: 'Scaffold a new engine',
        usage: 'create:engine <id> <name>',
        handler: async (args: string[]) => {
          const [id, name] = args;
          return this.scaffoldEngine({ engineId: id ?? 'engine-unknown', name: name ?? 'Unnamed Engine', category: 'other', capabilities: [] as any });
        },
      });
    } catch (e) {
      // ignore duplicate registration in tests or repeated instantiation
    }
  }

  registerCLICommand(command: CLICommandDescriptor): void {
    if (this.commands.has(command.name)) throw new Error(`Command ${command.name} is already registered`);
    this.commands.set(command.name, command);
  }

  listCommands(): CLICommandDescriptor[] {
    return Array.from(this.commands.values());
  }

  async executeCommand(name: string, args: string[]): Promise<ScaffoldResult | void> {
    const command = this.commands.get(name);
    if (!command) throw new Error(`Unknown CLI command ${name}`);
    return command.handler(args);
  }

  async scaffoldProject(options: ProjectScaffoldOptions): Promise<ScaffoldResult> {
    const artifacts = [
      { path: `${options.destination ?? '.'}/${options.projectName}/README.md`, content: `# ${options.projectName}\n\n${options.description}\n` },
      { path: `${options.destination ?? '.'}/${options.projectName}/package.json`, content: JSON.stringify({ name: options.projectName, version: '0.1.0', description: options.description, scripts: { start: 'npm run dev' } }, null, 2) },
    ];
    return { success: true, message: 'Project scaffold generated', artifacts, metadata: { options } };
  }

  async scaffoldPlugin(options: PluginScaffoldOptions): Promise<ScaffoldResult> {
    const artifacts = [
      { path: `plugins/${options.pluginId}/manifest.json`, content: JSON.stringify({ id: options.pluginId, name: options.name, version: options.version ?? '0.1.0', description: options.description, capabilities: options.capabilities?.map((cap) => cap.capabilityId) ?? [] }, null, 2) },
    ];
    // register capabilities with capability registry if available
    try {
      for (const cap of options.capabilities ?? []) {
        this.options?.capabilityRegistry?.register(cap as any);
      }
    } catch (e) {
      // noop - registry may not be provided in test contexts
    }

    // register a basic benchmark suite for this plugin with the evaluation engine if present
    try {
      if (this.options?.evaluationEngine) {
        const suite = {
          suiteId: `bench.plugin.${options.pluginId}`,
          name: `Plugin ${options.name} basic benchmark`,
          description: `Auto-generated benchmark for plugin ${options.pluginId}`,
          category: 'plugin',
          version: options.version ?? '0.1.0',
          supportedTargets: ['plugin'] as any,
          pluginId: options.pluginId,
          execute: async (context: any) => ({
            suiteId: `bench.plugin.${options.pluginId}`,
            benchmarkId: `bench.plugin.${options.pluginId}`,
            targetId: options.pluginId,
            targetType: 'plugin' as any,
            success: true,
            durationMs: 0,
            metrics: [],
            score: 100,
            details: 'auto-registered benchmark (no-op)',
            timestamp: new Date().toISOString(),
          }),
        } as any;
        this.options.evaluationEngine.registerSuite(suite);
      }
    } catch (e) {
      // noop
    }

    return { success: true, message: 'Plugin scaffold generated', artifacts, metadata: { options } };
  }

  async scaffoldAgent(options: AgentScaffoldOptions): Promise<ScaffoldResult> {
    const artifacts = [
      { path: `agents/${options.agentId}/agent.json`, content: JSON.stringify({ agentId: options.agentId, name: options.name, role: options.role, capabilities: options.capabilities, description: options.description }, null, 2) },
    ];
    return { success: true, message: 'Agent scaffold generated', artifacts, metadata: { options } };
  }

  async scaffoldEngine(options: EngineScaffoldOptions): Promise<ScaffoldResult> {
    const artifacts = [
      { path: `engines/${options.engineId}/engine.json`, content: JSON.stringify({ engineId: options.engineId, name: options.name, category: options.category, capabilities: options.capabilities.map((cap) => cap.capabilityId), description: options.description }, null, 2) },
    ];
    // register engine capabilities with capability registry if available
    try {
      for (const cap of options.capabilities ?? []) {
        this.options?.capabilityRegistry?.register(cap as any);
      }
    } catch (e) {
      // noop
    }

    // register a basic benchmark suite for this engine with the evaluation engine if present
    try {
      if (this.options?.evaluationEngine) {
        const suite = {
          suiteId: `bench.engine.${options.engineId}`,
          name: `Engine ${options.name} basic benchmark`,
          description: `Auto-generated benchmark for engine ${options.engineId}`,
          category: 'engine',
          version: '0.1.0',
          supportedTargets: ['engine'] as any,
          pluginId: undefined,
          execute: async (context: any) => ({
            suiteId: `bench.engine.${options.engineId}`,
            benchmarkId: `bench.engine.${options.engineId}`,
            targetId: options.engineId,
            targetType: 'engine' as any,
            success: true,
            durationMs: 0,
            metrics: [],
            score: 100,
            details: 'auto-registered benchmark (no-op)',
            timestamp: new Date().toISOString(),
          }),
        } as any;
        this.options.evaluationEngine.registerSuite(suite);
      }
    } catch (e) {
      // noop
    }

    return { success: true, message: 'Engine scaffold generated', artifacts, metadata: { options } };
  }

  async scaffoldWorkflow(options: WorkflowScaffoldOptions): Promise<ScaffoldResult> {
    const artifacts = [
      { path: `workflows/${options.workflowId}/workflow.json`, content: JSON.stringify({ workflowId: options.workflowId, name: options.name, description: options.description, triggers: options.triggers ?? [] }, null, 2) },
    ];
    return { success: true, message: 'Workflow scaffold generated', artifacts, metadata: { options } };
  }

  async scaffoldDocumentation(options: DocumentationScaffoldOptions): Promise<ScaffoldResult> {
    const artifacts = [
      { path: `docs/${options.title.replace(/\s+/g, '-').toLowerCase()}.md`, content: `# ${options.title}\n\n${options.description}\n` },
    ];
    return { success: true, message: 'Documentation scaffold generated', artifacts, metadata: { options } };
  }
}
