/**
 * DocumentViewer — Renders AI-generated documents with proper formatting
 * Shows formatted preview in chat + download buttons for Word/PDF/TXT/HTML/MD
 */
import React, { useCallback, useState } from 'react';
import { Download, FileText, ChevronDown, ChevronUp } from 'lucide-react';

interface DocumentViewerProps {
  title: string;
  content: string;
  format?: 'word' | 'text' | 'markdown' | 'html' | 'pdf';
}

/** Convert markdown-ish content to styled HTML for preview */
function contentToHtml(text: string): string {
  return text
    .replace(/^# (.+)$/gm, '<h1 style="font-size:1.4em;font-weight:700;color:#008751;margin:16px 0 8px;border-bottom:2px solid #008751;padding-bottom:4px">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 style="font-size:1.15em;font-weight:600;color:#005c38;margin:14px 0 6px">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="font-size:1.05em;font-weight:600;color:#007040;margin:10px 0 4px">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^[-•]\s+(.+)$/gm, '<li style="margin:3px 0;padding-left:4px">$1</li>')
    .replace(/^(\d+)\.\s+(.+)$/gm, '<li style="margin:3px 0;padding-left:4px">$2</li>')
    .replace(/\n\n+/g, '</p><p style="margin:8px 0;text-align:justify;line-height:1.7">')
    .replace(/\n/g, '<br/>');
}

export default function DocumentViewer({ title, content, format = 'text' }: DocumentViewerProps) {
  const [expanded, setExpanded] = useState(false);
  const [downloading, setDownloading] = useState<string | null>(null);

  const safeTitle = title.replace(/[/\\?%*:|"<>]/g, '-').slice(0, 60);

  // Clean content — unescape \n sequences from JSON
  const cleanContent = content
    .replace(/\\n/g, '\n')
    .replace(/\\t/g, '  ')
    .replace(/\\"/g, '"')
    .trim();

  const preview = expanded ? cleanContent : cleanContent.slice(0, 600) + (cleanContent.length > 600 ? '...' : '');

  // ── Download TXT ────────────────────────────────────────────────────────
  const downloadTXT = useCallback(() => {
    const blob = new Blob([cleanContent], { type: 'text/plain;charset=utf-8' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob); a.download = `${safeTitle}.txt`; a.click();
    URL.revokeObjectURL(a.href);
  }, [cleanContent, safeTitle]);

  // ── Download MD ─────────────────────────────────────────────────────────
  const downloadMD = useCallback(() => {
    const blob = new Blob([cleanContent], { type: 'text/markdown;charset=utf-8' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob); a.download = `${safeTitle}.md`; a.click();
    URL.revokeObjectURL(a.href);
  }, [cleanContent, safeTitle]);

  // ── Download HTML ───────────────────────────────────────────────────────
  const downloadHTML = useCallback(() => {
    const body = contentToHtml(cleanContent);
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    body{font-family:'Segoe UI',Arial,sans-serif;max-width:800px;margin:40px auto;padding:0 24px;color:#111;line-height:1.8;font-size:14px}
    h1{color:#008751;border-bottom:2px solid #008751;padding-bottom:6px}
    h2{color:#005c38;margin-top:24px}h3{color:#007040}
    p{text-align:justify;margin:10px 0}
    ul,ol{padding-left:24px}li{margin:4px 0}
    .footer{margin-top:48px;font-size:11px;color:#999;text-align:center;border-top:1px solid #eee;padding-top:14px}
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p style="text-align:justify;line-height:1.8">${body}</p>
  <div class="footer">Generated by BLACK AI — Africa's Smartest AI · blackai.vercel.app</div>
</body>
</html>`;
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob); a.download = `${safeTitle}.html`; a.click();
    URL.revokeObjectURL(a.href);
  }, [cleanContent, title, safeTitle]);

  // ── Download Word (.docx) ───────────────────────────────────────────────
  const downloadDOCX = useCallback(async () => {
    setDownloading('docx');
    try {
      const lines = cleanContent.split('\n');
      const xmlParagraphs = lines.map(line => {
        if (!line.trim()) return '<w:p/>';
        if (line.startsWith('# '))   return `<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>${esc(line.slice(2))}</w:t></w:r></w:p>`;
        if (line.startsWith('## '))  return `<w:p><w:pPr><w:pStyle w:val="Heading2"/></w:pPr><w:r><w:t>${esc(line.slice(3))}</w:t></w:r></w:p>`;
        if (line.startsWith('### ')) return `<w:p><w:pPr><w:pStyle w:val="Heading3"/></w:pPr><w:r><w:t>${esc(line.slice(4))}</w:t></w:r></w:p>`;
        if (/^[-•]\s/.test(line))    return `<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr></w:pPr><w:r><w:t>${esc(line.slice(2))}</w:t></w:r></w:p>`;
        return `<w:p><w:pPr><w:jc w:val="both"/></w:pPr><w:r><w:t xml:space="preserve">${esc(line)}</w:t></w:r></w:p>`;
      }).join('\n');

      const docXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:body>
<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>${esc(title)}</w:t></w:r></w:p>
${xmlParagraphs}
<w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:rPr><w:color w:val="888888"/><w:sz w:val="16"/></w:rPr><w:t>Generated by BLACK AI — Africa's Smartest AI</w:t></w:r></w:p>
<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>
</w:body></w:document>`;

      const stylesXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="24"/></w:rPr></w:rPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:b/><w:sz w:val="48"/><w:color w:val="008751"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:rPr><w:b/><w:sz w:val="36"/><w:color w:val="008751"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:rPr><w:b/><w:sz w:val="28"/><w:color w:val="005c38"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading3"><w:name w:val="heading 3"/><w:rPr><w:b/><w:sz w:val="24"/><w:color w:val="007040"/></w:rPr></w:style>
<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:pPr><w:jc w:val="both"/></w:pPr></w:style>
</w:styles>`;

      const JSZip = (await import('jszip')).default;
      const zip = new JSZip();
      zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>`);
      zip.file('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`);
      zip.file('word/document.xml', docXml);
      zip.file('word/styles.xml', stylesXml);
      zip.file('word/_rels/document.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
      const blob = await zip.generateAsync({ type: 'blob', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob); a.download = `${safeTitle}.docx`; a.click();
      URL.revokeObjectURL(a.href);
    } catch { downloadTXT(); }
    finally { setDownloading(null); }
  }, [cleanContent, title, safeTitle, downloadTXT]);

  // ── Download PDF (print dialog) ─────────────────────────────────────────
  const downloadPDF = useCallback(() => {
    setDownloading('pdf');
    const body = contentToHtml(cleanContent);
    const w = window.open('', '_blank');
    if (!w) { setDownloading(null); return; }
    w.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title>
<style>@media print{body{margin:0}}body{font-family:'Segoe UI',Arial,sans-serif;max-width:760px;margin:30px auto;padding:0 20px;color:#111;line-height:1.8;font-size:13px}h1{color:#008751;font-size:20px;border-bottom:2px solid #008751;padding-bottom:5px;margin-bottom:16px}h2{color:#005c38;font-size:16px;margin-top:20px}h3{color:#007040;font-size:14px}p{text-align:justify;margin:8px 0}ul,ol{padding-left:20px}li{margin:3px 0}.footer{margin-top:40px;font-size:10px;color:#aaa;text-align:center;border-top:1px solid #eee;padding-top:12px}</style>
</head><body><h1>${title}</h1><p style="text-align:justify;line-height:1.8">${body}</p>
<div class="footer">Generated by BLACK AI — Africa's Smartest AI · blackai.vercel.app</div>
</body></html>`);
    w.document.close();
    setTimeout(() => { w.print(); w.close(); setDownloading(null); }, 500);
  }, [cleanContent, title]);

  return (
    <div className="w-full max-w-full rounded-2xl overflow-hidden border border-[#008751]/25 shadow-lg bg-white">
      {/* Header */}
      <div className="px-4 py-2.5 bg-[#008751]/8 border-b border-[#008751]/15 flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2 min-w-0">
          <FileText size={15} className="text-[#008751] flex-shrink-0" />
          <span className="text-sm font-bold text-[#008751] truncate max-w-[200px]">{title}</span>
          <span className="text-[10px] text-gray-400 hidden sm:inline">{cleanContent.length.toLocaleString()} chars</span>
        </div>
        <div className="flex items-center gap-1 flex-wrap">
          {[
            { label: 'Word', fn: downloadDOCX, loading: downloading === 'docx' },
            { label: 'PDF',  fn: downloadPDF,  loading: downloading === 'pdf'  },
            { label: 'HTML', fn: downloadHTML, loading: false },
            { label: 'TXT',  fn: downloadTXT,  loading: false },
            { label: 'MD',   fn: downloadMD,   loading: false },
          ].map(({ label, fn, loading }) => (
            <button key={label} onClick={fn} disabled={loading}
              className="flex items-center gap-0.5 px-2 py-1 text-[10px] font-bold text-[#008751] border border-[#008751]/30 rounded-lg hover:bg-[#008751]/10 transition-colors disabled:opacity-50">
              <Download size={9} /> {loading ? '...' : label}
            </button>
          ))}
        </div>
      </div>

      {/* Formatted document preview */}
      <div className="p-5 bg-white max-h-[480px] overflow-y-auto">
        <div
          className="text-sm text-gray-800 leading-relaxed"
          style={{ textAlign: 'justify' }}
          dangerouslySetInnerHTML={{ __html: `<p style="text-align:justify;line-height:1.8;margin:0">${contentToHtml(preview)}</p>` }}
        />
        {cleanContent.length > 600 && (
          <button onClick={() => setExpanded(e => !e)}
            className="mt-3 flex items-center gap-1 text-[11px] text-[#008751] font-semibold hover:underline">
            {expanded ? <><ChevronUp size={12}/> Show less</> : <><ChevronDown size={12}/> Read full document</>}
          </button>
        )}
      </div>
    </div>
  );
}

function esc(s: string): string {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
}
